---
title: Pradera relajante
hero_image: images/banner.png
description: descripción de pradera relajante
version: 4
listed: false
copyedit: false
last_tested: "2020-05-04"
steps:
  - 
    title: Introducción
  - 
    title: Crea tu pradera

