---
title: Mindful meadow
hero_image: images/banner.png
description: Blumen-Wiesen Beschreibung
version: 4
listed: false
copyedit: false
last_tested: '2020-05-04'
steps:
  - 
    title: Einleitung
  - 
    title: Resize your flower
  - 
    title: Make more flowers
  - 
    title: Keeping on the grass
  - 
    title: Colour and size
  - 
    title: "Challenge: More sprites or a stary sky"
    challenge: true
  - 
    title: What next ?
